### ISSUE TITLE
The tests doesn't pass anymore!!

### ISSUE THREAD

**Issue by MarianaSavoldi** [taylonr/ps-sinonjs#1]
Hello, I'm watching the `SinonJS Fundamentals` at Pluralsight's plataform and I can't go on with the course because of the tests.
No matter what I do, following the step-by-step or not, any of the tests pass neither fail, they just get the "Timeout" error, even with the app AND database running...

Here's a print of my terminal output:
![Screenshot from 2022-05-04 16-06-04](https://user-images.githubusercontent.com/78616965/166808806-74ede756-57d6-4b9f-993c-50ab3c538708.png)

I simply have to stop the course by now :/

Ps: All the versions I'm using are the same of the course.

**Comment by taylonr** [comment]
While I'm looking in to this, if you're mostly trying to learn about SInon, there's another course that covers Mocking Node JS with Sinon (https://app.pluralsight.com/library/courses/mocking-nodejs-sinon/table-of-contents) and should cover a lot of the same topics.

**Comment by taylonr** [comment]
Ok the issue was the `pg` library. Even though your DB was running, it probably didn't have any data in it (or at least that's what happened when I started from scratch today.)

I ran `npm install pg@latest` and then ran `npm run db:create` again and it did the migration etc successfully and the tests ran.

I have updated all the branches to the latest version of the `pg` library.

For your own local copy, you can either pull down the changes and run `npm install` or just run `npm install pg@latest` and then run `npm run db:create`. If that gives you an error telling you the database already exists then just run
`npm run db:migrate` followed by `npm run db:seed` and you should be good to go.

**Comment by MarianaSavoldi** [comment]
Thank you!! :smile:
